# Generated by Django 3.2 on 2021-05-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Gamer',
            new_name='EventGamer',
        ),
        migrations.RenameModel(
            old_name='Game_Type',
            new_name='GameType',
        ),
    ]
