# Generated by Django 3.2.1 on 2021-05-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210506_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgamer',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventgamer',
            name='gamer_id',
        ),
        migrations.AddField(
            model_name='eventgamer',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.event'),
        ),
        migrations.AddField(
            model_name='eventgamer',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
        ),
    ]
